version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.17.4
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update NPM
          command: sudo npm install -g npm@6.14.14
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Application
          command: cd vite-aws-terraform-app && npm run build
      - aws-s3/sync:
          from: dist
          to: s3://vite-aws-website-bucket
          arguments: |
            --delete
workflows:
  main:
    jobs:
      - build-and-test:
          context: gh-dev
          filters:
            branches:
              only:
                - 'circleci'
