version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:14.17.4
    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          key: dependency-cache-{{ checksum "vite-aws-terraform-app/package-lock.json" }}
      - run:
          name: Install Packages
          command: |
            cd vite-aws-terraform-app
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "vite-aws-terraform-app/package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Application
          command: |
            # push artifacts on "dark" subdomain, and set environment variables before running `cf start`.
            ls -la
            cd vite-aws-terraform-app
            npm run build
      - aws-s3/sync:
          from: vite-aws-terraform-app/dist
          to: s3://vite-aws-website-bucket
          arguments: |
            --delete
workflows:
  main:
    jobs:
      - build-and-deploy:
          context: vite-demo
          filters:
            branches:
              only:
                - 'main'
